### ISSUE TITLE
Cound you please describe the procedure to set it up in more detailed way if you don't mind?

### ISSUE THREAD

**Issue by soarcreator** [willardf/Hazel-Examples#2]
I'm trying to make your Hazel-Networking example run on my Unity project and on my VPS.
I could fix the reference to Hazel in this example project, and the build has been successful.

However, it seems a little bit obscure to configure the server's IP address in my Unity project and where to put the "HazelServer.exe" file resulted from the build.

Or can this example run just on a local host?
I still don't understand what I can do completely with this Hazel-Examples repository.

I think I'll get a clear image of what the Hazel is once I see this example project working properly.

Thank you for your great work on Hazel for Unity!

**Comment by soarcreator** [comment]
Now, I guess this library is only for Windows...probably.

As far as I research, I found a sentence that said that the library doesn't work along in Mono, only in .NET.
Therefore, I guess if I execute "HazelServer.exe" on Windows computer, the GameObject in Unity can connect to a local host server.

But since my computer is Mac OSX, there is no way to see what would happen if this example project works properly, right?
I want a simple answer about this. But it seems nobody will react to this question...

**Comment by soarcreator** [comment]
With Mono Develop, I could get it to run on Mac OSX and Linux.

**Comment by Hazephyr** [comment]
> With Mono Develop, I could get it to run on Mac OSX and Linux.

Hi, how did you get it running on macOS? I am wondering if I can get this example to run on macOS on a local host
